spring:
  application:
    name: library
  profiles:
    active: prod
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    resources:


cloud:
  aws:
    stack:
      auto: false
    region:
      static: us-east-1

dynamo:
  readCapacity: 1000
  writeCapacity: 1000
